name: JSON Arifact Creator
run-name: Run by to ${{ inputs.UUID }}
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      UUID:
        description: 'Unique ID'
        required: true
        type: string
jobs:
  save-artifact-job:
    runs-on: ubuntu-latest
    name: Save output
    steps:
      - shell: bash
        run: |
          curl https://mocki.io/v1/d4867d8b-b5d5-4a48-a4ab-79131b5809b8 > output1.json
          echo output1.json
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output2
          path: output1.json        
