run-name:  Run by to @${{ github.actor }}
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  running-bash-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #- run: ./.github/scripts/build.sh
      - run: ls
        shell: bash
