run-name:  Run by to ${{ inputs.UUID }}
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      UUID:
        description: 'Unique ID'
        required: true
        type: string

jobs:
  running-bash-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #- run: ./.github/scripts/build.sh
      - run: ls
        shell: bash
