name:  Sleepy Workflow  # Give your workflow a descriptive name

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  running-bash-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #- run: ./.github/scripts/build.sh
      - run: sleep 30m
        shell: bash
